name: Deploy Game

on:
  push:
    branches:
      # Only on main branch
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # Specify all desired node versions
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Setup Tweego
        run: go get github.com/tmedwards/tweego

      - name: Spindle Build
        run: |
          yarn install
          yarn run spindle

      - name: Prepare Deploy Package
        run: |
          mkdir dist
          mv output/cellar-crawl.html dist/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # The branch the action should deploy to.
          FOLDER: dist      # The folder the action should deploy.
